replicaCount: ${replica_count}

serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: "${gcp_service_account}"

ingress:
  enabled: ${ingress_enabled}
  annotations:
    kubernetes.io/ingress.allow-http: "${ingress_allow_http}"
    kubernetes.io/ingress.global-static-ip-name: "${gcp_ip_address}"
    ingress.gcp.kubernetes.io/pre-shared-cert: "${gcp_ssl_cert}"
  hosts:
    - host: ""
      paths:
        - path: /*
          pathType: ImplementationSpecific

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 1Gi

backendConfig:
  enabled: true

env:
  SPRING_PROFILES_ACTIVE: "gcp"
  SECRET_PREFIX: "${secret_prefix}"
