# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      spring:
        patterns:
          - "org.springframework.boot:*"
          - "org.springdoc:*"
          - "com.google.cloud:spring-cloud-gcp-dependencies"
    ignore:
      - dependency-name: "io.socket:socket.io-client"
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "npm"
    directory: "/src/main/nodejs"
    schedule:
      interval: "monthly"
    groups:
      angular:
        patterns:
          - "@angular*"
      testing:
        patterns:
          - "@types/jasmine"
          - "jasmine*"
          - "karma*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
