steps:
- name: 'eclipse-temurin:17-jdk'
  entrypoint: './mvnw'
  args: ['-B', '-Dfrontend-build', '-Ddocker-build', '-DskipTests', 'verify']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/docker/karaplan:$BRANCH_NAME', '.']
  dir: 'target/docker-build'
images: ['europe-west1-docker.pkg.dev/$PROJECT_ID/docker/karaplan:$BRANCH_NAME']
artifacts:
  objects:
    location: 'gs://$PROJECT_ID/karaplan/'
    paths: ['target/karaplan.war']
