spring:
  datasource:
    username: karaplan
    password: "toComplete"
    url: "jdbc:mysql:///karaplan?useSSL=false&socketFactory=com.google.cloud.sql.mysql.SocketFactory&cloudSqlInstance=toComplete"
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "toComplete"
            client-secret: "toComplete"
          github:
            client-id: "toComplete"
            client-secret: "toComplete"
          facebook:
            client-id: "toComplete"
            client-secret: "toComplete"
