{{- if .Values.backendConfig.enabled -}}
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: {{ include "karaplan.fullname" . }}
  labels:
{{ include "karaplan.labels" . | indent 4 }}
spec:
  timeoutSec: 30
  connectionDraining:
    drainingTimeoutSec: 60
{{- end }}
