apiVersion: v1
kind: Service
metadata:
  name: {{ include "karaplan.fullname" . }}
  labels:
    {{- include "karaplan.labels" . | nindent 4 }}
  {{- if or .Values.service.annotations .Values.backendConfig.enabled }}
  annotations:
    {{- if .Values.service.annotations }}
    {{- toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.backendConfig.enabled }}
    cloud.google.com/neg: '{"ingress":{{ .Values.ingress.enabled }}}'
    cloud.google.com/backend-config: '{"ports":{"http":"{{ include "karaplan.fullname" . }}"}}'
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "karaplan.selectorLabels" . | nindent 4 }}
